name: Compile Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Build
        continue-on-error: true
        run: |
          export QMK_HOME='~/qmk_firmware'
          pip install milc
          python3 -m pip install --user qmk
          qmk setup -y
          ls ~/qmk_firmware
          cp -r ~/work/qmk-neo65/qmk-neo65/keyboards ~/qmk_firmware/
          qmk compile -kb neo/neo65/ansi -km default

      - name: Copy assets to Repo
        run: |
          rm -f $GITHUB_WORKSPACE/*.hex
          rm -f $GITHUB_WORKSPACE/*.bin
          find ~/qmk_firmware -maxdepth 1 -name "*.hex" -exec \cp '{}' $GITHUB_WORKSPACE \;
          find ~/qmk_firmware -maxdepth 1 -name "*.bin" -exec \cp '{}' $GITHUB_WORKSPACE \;
          ls $GITHUB_WORKSPACE

      - name: Set Release Date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Package assets
        run: |
          mkdir ~/qmk_firmware/firmware
          find ~/qmk_firmware -maxdepth 1 -name "*.hex" -exec mv '{}' ~/qmk_firmware/firmware \;
          find ~/qmk_firmware -maxdepth 1 -name "*.bin" -exec mv '{}' ~/qmk_firmware/firmware \;

      - name: Create release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.RELEASE_DATE }}
          prerelease: false
          draft: false

      - name: Upload assets
        uses: actions/upload-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: /home/runner/qmk_firmware/firmware/
          name: neo_neo65_ansi_default.bin
